FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 python3-pip libpq-dev libcurl4-openssl-dev libssl-dev

RUN pip3 install pipenv

WORKDIR /app

COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

COPY bin bin
COPY out out
COPY ticket_overflow ticket_overflow
COPY ticket_overflow/users.json ticket_overflow/users.json

CMD ["flask", "--app", "ticket_overflow", "run", "--debug", "--host", "0.0.0.0", "--port", "6400"]