DATE_FORMAT = "%Y-%m-%d"

CONCERT_STATUS = ["ACTIVE", "CANCELLED", "SOLD_OUT"]
CONCERT_ACTIVE = CONCERT_STATUS[0]
CONCERT_CANCELLED = CONCERT_STATUS[1]
CONCERT_SOLD_OUT = CONCERT_STATUS[2]

CONCERT_URL = "http://tickets.api.ticketoverflow.com/api/v1/concerts"


TICKET_PRINT_STATUS = ["NOT_PRINTED", "PRINTED", "ERROR", "PENDING"]
TICKET_NOT_PRINTED = TICKET_PRINT_STATUS[0]
TICKET_PRINTED = TICKET_PRINT_STATUS[1]
TICKET_ERROR = TICKET_PRINT_STATUS[2]
TICKET_PENDING = TICKET_PRINT_STATUS[3]

TICKET_URL = "http://tickets.api.ticketoverflow.com/api/v1/tickets"

USER_URL = "http://tickets.api.ticketoverflow.com/api/v1/users"

HAMILTON_TICKET_GEN = "ticket"
HAMILTON_SEATING_GEN = "seating"